# Generated by Django 4.2.21 on 2025-05-09 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tracked', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('codename', models.CharField(blank=True, max_length=100)),
                ('archived', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.storagelocation')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedItemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='StorageMedium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.storagemedium')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storagelocation')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='storage_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storagelocation'),
        ),
        migrations.AddField(
            model_name='item',
            name='storage_medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storagemedium'),
        ),
    ]
