# Generated by Django 4.2.21 on 2025-05-25 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quantityhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantityhistory',
            old_name='quantity_changed',
            new_name='change',
        ),
        migrations.RemoveField(
            model_name='quantityhistory',
            name='change_type',
        ),
        migrations.AddField(
            model_name='quantityhistory',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quantityhistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
    ]
